# Generated by Django 2.0.6 on 2018-08-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'направление деятельности',
                'verbose_name_plural': 'Направления деятельности',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('contract_date', models.DateField(auto_now_add=True, verbose_name='Дата договора')),
                ('vats_number', models.CharField(max_length=20, verbose_name='Номер ВАТС')),
                ('login', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('contract_agree', models.BooleanField(default=False, verbose_name='Подтверждение договора')),
                ('activity_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_clients_app.ActivityDirection', verbose_name='Направление деятельности')),
            ],
            options={
                'verbose_name': 'парнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
    ]
