# Generated by Django 2.0.6 on 2018-08-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Средний чек')),
                ('prc_commission', models.SmallIntegerField(max_length=2, verbose_name='%')),
                ('max_commission', models.CharField(max_length=50, verbose_name='Но не более')),
            ],
            options={
                'verbose_name': 'комиссионное вознаграждение',
                'verbose_name_plural': 'Комиссионное вознаграждение',
            },
        ),
        migrations.AlterField(
            model_name='activitydirection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='activitydirection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
