# Generated by Django 2.0.6 on 2018-08-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0003_employeeadminsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='prc_commission',
            field=models.SmallIntegerField(verbose_name='%'),
        ),
    ]
