# Generated by Django 2.0.6 on 2018-08-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0006_auto_20180809_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadminsettings',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_clients_app.Employee', verbose_name='Работник'),
        ),
    ]
