# Generated by Django 2.0.6 on 2018-08-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0007_auto_20180809_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone_number', models.CharField(max_length=20, verbose_name='Номер клиента')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время звонка')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_clients_app.Employee', verbose_name='Партнёр')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Номер телефона')),
                ('registration_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(max_length=20, verbose_name='Номер клиента')),
                ('order_price', models.FloatField(verbose_name='Цена заявки')),
                ('payed', models.FloatField(default=0.0, verbose_name='Оплачено')),
                ('checking_act', models.BooleanField(default=False, verbose_name='Акт сверки')),
                ('rejecting', models.IntegerField(default=0, verbose_name='Отклонения')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_clients_app.Employee', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'заявка',
            },
        ),
        migrations.AlterModelOptions(
            name='employeeadminsettings',
            options={'verbose_name': 'план заказов', 'verbose_name_plural': 'Планы заказов'},
        ),
        migrations.AlterField(
            model_name='employeeadminsettings',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_clients_app.Employee', verbose_name='Партнёр'),
        ),
    ]
