# Generated by Django 2.0.6 on 2018-08-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0008_auto_20180809_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='checking_act',
            field=models.CharField(default='', max_length=300, verbose_name='Акт сверки'),
        ),
    ]
