# Generated by Django 2.0.6 on 2018-08-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0009_auto_20180809_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadminsettings',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
