# Generated by Django 2.0.6 on 2018-08-17 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0010_employeeadminsettings_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calls',
            options={'verbose_name': 'дзвонок клиента', 'verbose_name_plural': 'Дзвонки клиентов'},
        ),
        migrations.RemoveField(
            model_name='calls',
            name='client_phone_number',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='data_time',
        ),
        migrations.AddField(
            model_name='calls',
            name='count',
            field=models.IntegerField(default=0, verbose_name='К-во звонков'),
        ),
        migrations.AddField(
            model_name='calls',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 8, 17, 13, 52, 31, 781740), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='calls',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_clients_app.Employee', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_clients_app.Employee', verbose_name='Партнёр'),
        ),
    ]
