# Generated by Django 2.0.7 on 2018-08-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0013_auto_20180817_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='price',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='max_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное значение'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальное значение'),
        ),
    ]
