# Generated by Django 2.0.7 on 2018-08-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0014_auto_20180820_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='max_commission',
            field=models.PositiveIntegerField(default=9223372036854775807, verbose_name='Но не более'),
        ),
    ]
