# Generated by Django 2.0.7 on 2018-08-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0015_auto_20180820_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='max_commission',
            field=models.PositiveIntegerField(default=0, verbose_name='Но не более'),
        ),
    ]
