# Generated by Django 2.0.6 on 2018-08-29 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_clients_app', '0016_auto_20180820_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.RemoveField(
            model_name='orders',
            name='data_time',
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время заказа'),
            preserve_default=False,
        ),
    ]
